kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: etherpad-canary
spec:
  replicas: 1
  template:
    metadata:
      name: etherpad
      labels:
        app: etherpad
        env: canary
    spec:
      containers:
      - name: etherpad-lite
        image: gcr.io/ccc-etherpad-spinnakerdeploy/github.com/hannogrimm/etherpad-lite:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9001
          protocol: TCP
        env:
        - name: VERSION
          value: canary
